.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
Fixes #140 
Added Bug Report, Feature Request, and Pull Request templates.
=> Fix #140, Add Issue & PR Templates

CONTRIBUTING.md
Fixes #141 
Added contributing guide that directs users to the cFS CONTRIBUTING.md file.
=> Fix #141, Add Contributing Guide

.github/workflows/build-cfs.yml
Fixes #138 
Tested on fork: https://github.com/ArielSAdamsNASA/CF/runs/4940387579?check_suite_focus=true
Build cFS with the CF app and run ./core-cpu1
Ariel Adams, ASRC Federal
=> Fix #138, Add Build Workflow

unit-test/utilities/cf_test_utils.h
- Fix #188
CI
None
CI
None
None
=> Fix #188, Apply header guard standard

.github/workflows/build-cfs.yml
- Fix #190
CI
CI should pass
CI
None
None
=> Fix #190, Use lowercase and updated table name in CI

unit-test/cf_app_tests.c, unit-test/cf_chunk_tests.c, unit-test/cf_clist_tests.c, unit-test/cf_utils_tests.c
- Fix #197
Build 32 bit & run unit tests with valgrind 
No uninitialized variable warnings
- Hardware: i5/wsl
None
None
=> Fix #197, Resolve uninitialized variables in UT

fsw/src/cf_logical_pdu.h
- Fix #200 
CI and local build/execute of unit tests
None
CI
None
None
=> Fix #200, Follow include standard

unit-test/stubs/cf_app_global.c, unit-test/stubs/cf_cfdp_handlers.c, unit-test/stubs/cf_cfdp_sbintf_handlers.c, unit-test/stubs/cf_chunk_handlers.c, unit-test/stubs/cf_clist_handlers.c, unit-test/stubs/cf_cmd_handlers.c, unit-test/stubs/cf_utils_handlers.c
- Fix #207
CI, documentation only
None, documentation only
N/A
None
None
=> Fix #207, Remove old license headers

.github/workflows/unit-test-coverage.yml
- Fix #212 
CI w/ modified path/repo for reference: https://github.com/skliper/CF/actions/runs/2174432954
None
CI
nasa/cFS#459
None
=> Fix #212, Add unit test and coverage workflow

docs/cf_FunctionalRequirements.csv
- Fix #232 
- Fix #231
None, doc only
None
N/A
None
None
=> Fix #232 #231, Cleanup and add functional requirements csv

.github/workflows/codeql-build.yml
A clear and concise description of what the contribution is.
Added CodeQL to GitHub workflows
Fix #244 
1. Pushed to branch
2. Checked CodeQL ran successfully
no impact to behavior
Browser
Add any other context about the contribution here.
If included, identify any third party code and provide text file of license
Full name and company/organization/center of all contributors ("Personal" if individual work)
- Note CLA's apply to software contributions.
=> Fix #244, Add CodeQL

fsw/src/cf_events.h
- Part #206 
Added event ID documentation
- Fix #26 
Removed unused event ids
CI
None, just improved documentation and no unused event IDs
CI
Note, still working the rest of the documentation
None
=> Part #206, Fix #26, Document Event IDs and remove unused

unit-test/cf_cfdp_tests.c
Fix #290, bug in unit tests wasn't multiplying the number of transactions per channel by the number of channels, causing the unit test to not pass.
Ran unit test
All unit tests pass
=> Fix #290, updated value in assert causing test to fail

fsw/src/cf_chunk.c, fsw/src/cf_chunk.h, unit-test/cf_chunk_tests.c, unit-test/utilities/cf_test_utils.h
- Fix #293 
- Fix #306 
CI with "real" scenarios implemented (no longer random number)
Fixes both the chunk add and chunk gap logic
CI
None
None
=> Fix #293 #306, CF chunk unit test cleanup and main code chunk add and gap bug fixes

fsw/src/cf_msg.h
- Fix #311 
CI
Fixed size types in tlm
CI
None
None
Jacob Hageman - NASA/GSFC (via stakeholder request)
=> Fix #311, Use fixed size types in tlm EOT packet

unit-test/cf_clist_tests.c, unit-test/cf_crc_tests.c, unit-test/utilities/cf_test_utils.h
- Fix #315 
CI
Squash warnings... also more maintainable unit tests (much simpler)
CI
None
None
=> Fix #315, Remove dynamic memory use in UTs

fsw/src/cf_cfdp_r.h
- Fix #322
Build doc with Ubuntu 20.04
Successful doc build
- Hardware: i5/Docker
- OS: Ubuntu 20.04
None
None
=> Fix #322, Resolve usersguide issues with doxygen 1.8.17

fsw/src/cf_cmd.c, fsw/src/cf_msg.h, unit-test/cf_cmd_tests.c, unit-test/utilities/cf_test_utils.h
Fix #263
Unit testing
no impact to behavior
=> Fix #263, define special values in cmd processing as enums

README.md
```diff
- #core Flight System (cFS) CFDP Application (CF)
+ # core Flight System (cFS) CFDP Application (CF)
```
=> Update README.md - Fixed Typo

docs/cf_FunctionalRequirements.csv
* [ x ] I reviewed the [Contributing Guide](https://github.com/nasa/CF/blob/main/CONTRIBUTING.md).
* [ x ] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.
Addresses #325.
Updates requirements to support transaction status codes indicating early completion.
N/A - documentation update
N/A - documentation update
Ubuntu 22.04
Dylan Baker, NASA-GSFC Code 582
=> Fix #325, update requirements for more concise transaction status code

docs/dox_src/cfs_cf.dox
Pushing doxygen update to refactor the CF User's Guide for @semaldona 
Build/Reviewed updated User's Guide
Dan Knutsen
NASA Goddard
=> Fix #352, User's Guide CleanUp
