fsw/src/cf_cfdp.c
This helper function was declared with fixed-length string arguments but in practice is used with other buffer lengths.  These arguments are changed to (more conventional) `const char *` instead.
Note that other cases where fixed-length string arguments are used are not changed by this commit, since it appears those are always used with a buffer of that length.
Fixes #43
=> Fix #43, correct declaration of CF_CFDP_PlaybackDir_

fsw/src/cf_cfdp.c
The call to CFE_SB_AllocateMessageBuffer needs to take into account the size of the extra SB header, not just the CF_MAX_PDU_SIZE.
Fixes #72
=> Fix #72, correct allocation size for CFDP PDU

fsw/src/cf_app.c, fsw/src/cf_cfdp.c, unit-test/cf_cfdp_tests.c
Check generically for CFE_SUCCESS, rather than a single error code, since there is more than one error.
This also corrects some minor coding standards items in cf_app.c - logic not really changed but improves readability.
Fixes #73
=> Fix #73, correct status checks of CFE_SB_ReceiveBuffer

fsw/src/cf_cfdp_pdu.h, unit-test/cf_cfdp_helpers_tests.c, unit-test/cf_cfdp_r_tests.c, unit-test/cf_cfdp_s_tests.c, unit-test/cf_cfdp_tests.c, unit-test/utilities/cf_test_utils.h
For unit unit tests that invoke CF PDU processing functions on either input or output, ensure that the locally instantiated
"dummy" PDU is both sized sufficiently and aligned correctly.
This removes quite a bit of questionable casting between the buffer types, and fixes a number of stack-smashing issues.
For completeness, this also clears (memset to 0) all instantiated buffers, before setting values in the test.  This ensures that the
entire message structure has predictable/repeatable content.
Fixes #44
Fixes #46
=> Fix #44, #46, instantiate properly sized and aligned buffers

unit-test/cf_cfdp_tests.c
Any data structure passed to a function by pointer where that pointer is documented as input-only (const)
should always be initialized.  Some compilers will warn about this (even if the called function does not actively
dereference the pointer due to other constraints).
Fixes #47
=> Fix #47, init data passed as const input

unit-test/cf_cfdp_tests.c
Correct the pipe ID assignment in UT to use the resourceID type.
This also uses a fixed/consistent value here, rather than a random value.  There is no real need to use a random value.
Fixes #48
=> Fix #48, use proper CFE_SB_PipeID type

unit-test/cf_cmd_tests.c
Where ever a unit test is generating a buffer on the stack to send to a command processing function, this typically needs to be represented as a CFE_SB_Buffer_t* pointer, which by definition is supposed to be aligned to the worst-possible case, which may be greater than the alignment requirement of the actual command type.
To avoid warnings when converting between types, use a union to ensure the stack object meets the alignment requirements for CFE_SB_Buffer_t.
Furthermore, ensure all buffers instantiated on the stack are cleared (memset to 0) before operating on them or passing them to a CF function.
Fixes #49
=> Fix #49, aligned buffer for all test commands

unit-test/cf_cmd_tests.c, unit-test/utilities/cf_test_utils.c, unit-test/utilities/cf_test_utils.h
Variables declared in headers should only be "extern", otherwise multiple instances will be defined.  This moves the instantiation
of variables to the most relevant C file.
Fixes #50
=> Fix #50, do not instantiate globals in header file

fsw/src/cf_assert.h
This effectively ignores CF_Assert checks in the code when it is compiled with NDEBUG.  None of these checks should be needed after development.
In particular, this removes the use of the non-standard "unlikely" compiler extension that was used here.
Fixes #51
=> Fix #51, do not assert when NDEBUG is set

unit-test/cf_cfdp_tests.c, unit-test/utilities/cf_test_utils.c
Instead of using the system assert call, use UtAssert_Abort() to report critical conditions where continuation is not possible.
Note due to limitations of the UtAssert_Abort() function, this uses UtAssert_Failed() to report any runtime information, followed by
abort with a static/fixed message.
Fixes #52
=> Fix #52, do not use system assert in tests

unit-test/cf_cfdp_tests.c
Whenever the value of a local variable not directly set by the test code, make sure to set it to a value so it is
never seen as uninitialized.
Some of these are simply cases where the value is initialized within a loop.  Several lines of code triggered warnings that a
value may be used uninitialized, because the compiler logic might not recognize that the loop must run at least once.
In other cases a local buffer structure should be cleared/memset to 0 before being passed along.
Fixes #53
=> Fix #53, initialize local variables

unit-test/cf_cfdp_tests.c
The test must not pass a buffer size larger than the actual buffer, or else it will read beyond the end.
Fixes #54
=> Fix #54, pass actual size of buffer

unit-test/cf_clist_tests.c
Initialize the variables at the beginning of the function.  They will be set again in the loop, but this avoids the compiler warning.
Fixes #55
=> Fix #55, resolve uninitialized pointer warning

CMakeLists.txt, unit-test/CMakeLists.txt
The application target should not have an "app" suffix.  Note that none of the other CFS apps have a suffix either, so this
makes CF consistent with that.
Also - this removes use of "aux_source_directory" - preference is to list the source files.
Fixes #88
=> Fix #88, consistent application target name

fsw/src/cf_cfdp_helpers.c, fsw/src/cf_cfdp_pdu.h, unit-test/cf_cfdp_helpers_tests.c, unit-test/stubs/cf_cfdp_helpers_stubs.c
Unused functions/dead code should not be included in FSW
Fixes #96
=> Fix #96, remove unused CF_EndOfHeaderPtr function

fsw/src/cf_cfdp.c, fsw/src/cf_cfdp.h, fsw/src/cf_cfdp_r.c, fsw/src/cf_cfdp_s.c, fsw/src/cf_cmd.c, fsw/src/cf_utils.c, fsw/src/cf_utils.h, unit-test/cf_cfdp_r_tests.c, unit-test/cf_cfdp_s_tests.c, unit-test/cf_cfdp_tests.c, unit-test/cf_cmd_tests.c, unit-test/cf_utils_tests.c
Bit field behavior is platform-specific, bits are not specified to be in any particular order. Furthermore, unions of bitfields are likely undefined behavior. 
This removes the bitfields and replaces with normal fields.
Fixes #67
NOTE: The cost of doing this is slightly larger data size.  I checked the size of the structure before and after to quantify this - the "flags" structure grew by 16 bytes on my dev system (x86-64, gcc 11.2).
The net result is that the memory footprint of the CF global grows by 1600 bytes (due to 100 transactions in default config).  However, this is partially mitigated by a slight reduction in code size, of approximately 300 bytes.  It probably runs faster too (although I did not quantify that - not as easy to test) but the 300 bytes of extra code were obviously …
=> Fix #67, remove use of bitfields in CF

fsw/src/cf_cfdp.h, fsw/src/cf_cfdp_r.c, fsw/src/cf_cfdp_s.c, unit-test/cf_cfdp_r_tests.c, unit-test/cf_cfdp_s_tests.c
Using a union for the ack/nak counts is somewhat dangerous because undefined behavior will occur if accessed improperly.  In this case there is no need to have separate representations of the counter, they are both limited to the "unit8" range, so use a uint8.
Fixes #113
=> Fix #113, replace acknack count union

fsw/src/cf_msg.h
The CMD/TLM structures are application-defined.  As such, they should not need to depend on compiler-specific extensions like packing.
Note that the definitions (mostly) already included explicit spare bytes where padding was likely to be needed, so the "packed" attribute was largely unnecessary here, only serving to make the definitions NOT compilant with C99.
Fixes #41
=> Fix #41, no packing of CMD/TLM structs

fsw/src/cf_app.c, unit-test/cf_app_tests.c
The TBL API may return success codes other than CFE_SUCCESS, such as CFE_TBL_INFO_UPDATED.  From the standpoint of CF_CheckTables, these should all be considered successful.
Fixes #66
=> Fix #66, handle alt-success code from TBL API

fsw/src/cf_cfdp.c, fsw/src/cf_cfdp.h, fsw/src/cf_cfdp_helpers.c, fsw/src/cf_cfdp_pdu.h, fsw/src/cf_cfdp_r.c, fsw/src/cf_cfdp_s.c, unit-test/cf_cfdp_helpers_tests.c, unit-test/cf_cfdp_r_tests.c, unit-test/cf_cfdp_s_tests.c, unit-test/cf_cfdp_tests.c, unit-test/stubs/cf_cfdp_helpers_stubs.c, unit-test/stubs/cf_cfdp_r_stubs.c, unit-test/stubs/cf_cfdp_s_stubs.c, unit-test/stubs/cf_cfdp_stubs.c
Standardize the dynamic handler functions to two basic types, one that accepts a PDU (recv) and one that does not (send).
Also create several dispatch table types, one based on file directive code, one based on Tx sub state, and one based
on Rx sub state.
Change the dispatcher functions to use these common types and create new dispatcher functions where there was not
a separate function already (this makes the pattern consistent).
Make all "receive" helper functions accept a pointer to the recieved PDU and actually use that pointer to read the data.  This
substantially reduces reliance on the global and fixes some cases where a pointer was actually passed into a function, but
ignored.  This takes a significant step toward removing the global entirely, but does not do so yet.
Fixes #111 …
=> Fix #111, make dispatch tables and functions consistent

fsw/src/cf_cfdp.c, unit-test/cf_cfdp_tests.c
Restores setting a global flag which was mistakenly deleted in a previous cleanup.  This also adds a unit test check to confirm the global was set false.
Fixes #161
Build CF and run tests
Engine gets disabled when CF_CFDP_DisableEngine is called
Ubuntu 21.10
=> Fix #161, disable the engine in CF_CFDP_DisableEngine

fsw/src/cf_cfdp.c, fsw/src/cf_events.h, unit-test/cf_cfdp_tests.c
The CF does not currently interpret/use the segment metadata option inside file data PDUs.  Packets with this bit set should
be rejected.
Fixes #129
Build CF and run all tests
Execute test file transfers between two CFE nodes
None, CF does not set this bit on Tx, it should never be set on Rx.
Ubuntu 21.10
=> Fix #129, reject FD packets with segment_metadata flag set

fsw/src/cf_cfdp.c, fsw/src/cf_cfdp.h, fsw/src/cf_cfdp_r.c, fsw/src/cf_chunk.c, fsw/src/cf_chunk.h, fsw/src/cf_cmd.c, fsw/src/cf_cmd.h, fsw/src/cf_utils.c, fsw/src/cf_utils.h, unit-test/cf_cfdp_r_tests.c, unit-test/cf_cfdp_tests.c, unit-test/cf_cmd_tests.c, unit-test/cf_utils_tests.c, unit-test/stubs/cf_cfdp_stubs.c, unit-test/stubs/cf_chunk_stubs.c, unit-test/stubs/cf_cmd_stubs.c, unit-test/stubs/cf_utils_stubs.c, unit-test/utilities/cf_test_alt_handler.c
Renames all remaining identifiers that did not have an appropriate name per the coding standards.  Specifically, this is anything
that did not start with CF prefix (#149) and anything that ended with an underscore only (#110).
Fixes #149 
Fixes #110
Build and sanity check CF, run all tests
Execute test file transfer between two CFE nodes
None, internal symbol rename only
Ubuntu 21.10
=> Fix #110, #149, update identifier names

fsw/src/cf_msg.h
Add explicit spare bytes where the compiler is likely to introduce padding into hte message structures.  CFS SB messages should avoid having any implicit padding, whenever possible.
Fixes #157
Build and run tests, send some commands to sanity check
None really, the padding was implicitly in the messages already, this just makes it clear/explicit.
Ubuntu 21.04 (on 64-bit CPU)
This probably needs COSMOS updates as well (TBD)
=> Fix #157, adjust padding in msg structs

CMakeLists.txt, fsw/platform_inc/cf_platform_cfg.h, fsw/src/cf_crc.c, fsw/src/cf_verify.h
Removes the checksum "optimization" for big endian, as it is unlikely to be useful and creates endianness dependencies.
Fixes #61
None on x86/little endian (removes code that was not used)
PPC/big endian will use the same code as x86, might be a bit slower but its safer and more testable (because its the same code)
Ubuntu 21.10
The big endian optimization is probably not that useful because it requires that the HW can do misaligned 32-bit reads.  AFAIK most embedded CPUs do not have this capability, and if they can, it might not be all that much faster than reading it byte-by-byte.  So even though it looks like a 32-bit read in C code …
=> Fix #61, remove dependence on ENDIAN macro for checksum

fsw/platform_inc/cf_platform_cfg.h, fsw/src/cf_msg.h
Entity IDs should be larger by default for real-world applicability, as this also restricts what CFDP can receive, not just what it sends.  Note CFDP will only use the number of bytes required to express the value, so values less than 256 will
still only use 1 byte, regardless of this config.  This just allows use of larger values.
Fixes #62
Default "out of the box" config should support entity ID values up to 32 bits.  
Ubuntu 21.10
This only affects what CF is capable of handling, if running with small (<256) entity ID values, there is no change to the runtime behavior at all; they will still be 8 bits in practice.
**Contributor Info …
=> Fix #62, make entity ID default to 32 bit

fsw/src/cf_cmd.c, fsw/src/cf_cmd.h, fsw/src/cf_msg.h, unit-test/cf_cmd_tests.c, unit-test/stubs/cf_cmd_stubs.c
Reworks the CF_CmdGetSetParam to be clearer in its implementation, not require the use of endian-specific conditionally-compiled code.
Fixes #63
Build and sanity test CF app
Send various get/set param commands (CC 10 and 11) and confirm working as expected
None visible externally (i.e. CMD handling) but much cleaner internal handling of these values.
Ubuntu 21.10
=> Fix #63, remove macros within C code

fsw/src/cf_cfdp.c
Modifies the loop inside this function to be more conventional, and easier to follow. Does not change the logic.
Fixes #60
Build and sanity check CF, run all tests
None, this does not change loop logic
Ubuntu 21.10
Do not use "goto" to jump _inside_ the middle of a loop, just use `while(true)` and break out when the stop condition was reached.
=> Fix #60, rework loop in CF_CFDP_CycleTx

fsw/tables/cf_def_config.c
Removes the throttle sem name from the example configuration table.  Unless the user provides another app/library to create this sem, this configuration will not load.  With this sem removed then CF should at least be able to start up.
Fixes #178
Build CF
Example config will not attempt to use a throttle sem.
Ubuntu 21.10
=> Fix #178, remove throttle sem from default/example config

fsw/src/cf_version.h
Per CFE/CFS versioning patterns, development software should report itself as revision 99 to avoid confusion with released versions.
Fixes #146
Revision reported as 99 now, example boot event:
EVS Port1 66/1/CF_APP 20: CF Initialized. Version 3.0.99
Ubuntu 21.04
=> Fix #146, set revision number to 99

fsw/src/cf_app.c, fsw/src/cf_cfdp.c, fsw/src/cf_cfdp_dispatch.c, fsw/src/cf_cfdp_r.c, fsw/src/cf_cfdp_s.c, fsw/src/cf_cmd.c, fsw/src/cf_utils.c, unit-test/cf_app_tests.c, unit-test/cf_chunk_tests.c, unit-test/cf_cmd_tests.c, unit-test/cf_crc_tests.c, unit-test/cf_timer_tests.c, unit-test/cf_utils_tests.c
Use the correct printf format code and typecast for printing various values in log messages and events.
Fixes #58
Build and run tests on RTEMS and 32-bit PowerPC 
Build succeeds without warnings or errors
RTEMS 4.11.3 on pc686 + QEMU
Yocto/Poky Linux on PPC 7400  + QEMU
=> Fix #58, scrub all printf format codes

fsw/src/cf_cfdp_types.h, unit-test/utilities/cf_test_utils.h
Use the correct typedef for OSAL ID.  This also necessitates using the correct conversion macro where use as an integer is intended.
Fixes #171
Build with OSAL bleeding edge code, confirm no type conversion errors.
None w/Caelum OSAL, as osal_id_t is equivalent to uint32.
Ubuntu 21.10
=> Fix #171, use osal_id_t for OSAL ID, not int32

fsw/src/cf_cfdp_s.c, unit-test/cf_cfdp_s_tests.c
This call got inadvertently removed with recent change, caught by regression test.  This puts it back.
Fixes #172
Execute CF file transfers
NAK should work properly again
Ubuntu 21.10
In my test environment it is difficult to recreate a NAK situation...
=> Fix #172, restore call to CF_CFDP_RecvNak

fsw/src/cf_msg.h
Adds missing enum label to CF_CMDS.
Fixes #36
Issued the command (code 21) from cmdutil and confirmed CF did something ....
None, this command code was already in the dispatch table, so it worked before if CC 21 was manually sent using cmdutil.
Ubuntu 21.10
This is just for completeness/correctness of the enum.
=> Fix #36, add CF_PURGE_QUEUE_CC

unit-test/cf_chunk_tests.c
Do not use a random uint16 to size the structure that is allocated on the stack.  Pick a reasonable size that is not likely to overrun
the stack, and use it.
This fixes a crash/stack overrun issue when running on RTEMS.
Fixes #164
Build and sanity check CF on PC-RTEMS
Tests pass
RTEMS 4.11.3 via QEMU+pc686 BSP
This _only_ fixes the random values that caused a stack overrun/crash.  Would still recommend fixing other use of random numbers in tests.
=> Fix #164, consistent "chunk" test sizes

fsw/src/cf_cmd.c, unit-test/cf_cmd_tests.c
For commands that rely on CF_TsnChanAction(), this is documented as returning a count of the number of transactions affected.  Therefore, a return value >0 means that the operation was successful (or at least it matched something), and a return value <=0 means failure.
- Fixes a case where the function did not adhere to its documented return
- Fixes passing the result to CF_CmdCond() which needs a translation.
Fixes #125
Correct counters being incremented now
Ubuntu 21.10
=> Fix #125, correct accept/reject counter increments

fsw/src/cf_cmd.c, fsw/src/cf_events.h, unit-test/cf_cmd_tests.c
The input parameters on TxFile and Playback commands was not being sufficiently validated before calling the internal routine.
Fixes #123
Fixes #126 
Send in commands with invalid parameters/channel number and confirm it is being rejected with the event.
CF no longer segfaults with an out-of-range channel number
Ubuntu 21.10
=> Fix #123, validate input params on TxFile and Playback cmds

fsw/src/cf_cmd.c, fsw/src/cf_utils.c, fsw/src/cf_utils.h, unit-test/cf_cmd_tests.c, unit-test/cf_utils_tests.c, unit-test/stubs/cf_utils_handlers.c, unit-test/stubs/cf_utils_stubs.c, unit-test/utilities/cf_test_alt_handler.c, unit-test/utilities/cf_test_alt_handler.h, unit-test/utilities/cf_test_utils.h
- rename the functions to better indicate what they do
- do not discard the part of the output that has EID/TSN/CC information
- do not pass the return value of snprintf directly to write(), use strlen()
- simplify the code
Fixes #40
Build and unit test CF.
Run two instances of CFE+CF, execute transfer in both directions and confirm
Issue CF_WRITE_QUEUE_CC (15) to write the transaction and history queues to the file
Confirm contents of the file are correct.
The file contains the information it is intended to contain, mainly the SEQ/DIR/PEER/CC bits are not omitted.  There is also no risk of buffer overruns.
Here is an example file output, after running two transactions between two nodes (one RX, one TX)
``` …
```
=> Fix #40, update traverse history/write file

fsw/src/cf_cfdp.c, fsw/src/cf_events.h, unit-test/cf_cfdp_tests.c
This bit indicates that the PDU has 64-bit size and offset fields. CF currently does not support large file sizes.  It needs to reject
these packets as they will corrupt the data because they are not decoded properly (decode is fixed at 32 bit sizes).
Fixes #95
Force sending PDU with bit set, confirm CF rejects the PDU.
CF informs the user that it received a PDU that it does not understand.
Ubuntu 21.10
CF does not and did not support this feature, the only difference here is that it CF will now properly detect and reject a received PDU with this bit set, and inform the user of that event, instead of attempting to ingest it and doing so …
=> Fix #95, reject PDUs with large bit set

fsw/src/cf_cmd.c, unit-test/cf_cmd_tests.c
Rewrites the unit test on this function in order to get full line coverage.
This needs to call the routine with every defined param ID to get each case.
Fixes #166
Build and run all unit tests, confirm coverage
None for FSW, unit test coverage improvement
Ubuntu 21.10
This also removes a bit of code from FSW that did a no-op for a size that wasn't uint32/uint16/uint8.  This was unreachable because there are no cases that have such a size, and it would be a software bug if there was.  
=> Fix #166, improve coverage on CF_CmdGetSetParam

fsw/tables/cf_def_config.c
* [ x] I reviewed the [Contributing Guide](https://github.com/nasa/CF/blob/main/CONTRIBUTING.md).
* [ x] I signed and emailed the appropriate Contributor License agreement to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.
- Fix #186 
Built and default startup, confirmed table loaded w/ no errors (with CF app name in startup config)
No polling errors reported, works with GSFC app naming patterns
- Hardware: i5/Docker
None
None
Jacob …
=> Fix #186, CF table name and default polling disabled

unit-test/cf_chunk_tests.c
- Fix #195 
Built/ran 32 bit unit tests
No longer stack smashing in UT
- Hardware: i5/Container
None
None
=> Fix #195, Stack smashing in CF_Chunk unit test

.github/workflows/format-check.yml, .github/workflows/static-analysis.yml
Fixes #93
Tested format check on fork: https://github.com/chillfig/CF/runs/5662467104?check_suite_focus=true
Tested static analysis on fork: https://github.com/chillfig/CF/runs/5662467266?check_suite_focus=true
Passing workflow
Ubuntu 18.04
The added format check workflow catches a format check error when it runs its "error on differences" step. Specifically, the workflow throws errors on the placement of "\*" with pointer variables written in the fsw and unit test files. The format check would rather that "\*" be on the left side of the whitespace than the right side.
**Contributor Info - All information REQUIRED …
=> Fix #93, Adds format check and static analysis workflows

.github/workflows/build-documentation.yml, docs/dox_src/cf-usersguide.doxyfile.in
- Fix #229
CI with forced fork/branch for reuse workflow and forced deploy: https://github.com/skliper/CF/runs/6009379924
Doc build with enforcement of no warnings, will deploy to gh-pages on push to main
CI
Depends on nasa/cFS#451
None
=> Fix #229, Add doc build/deploy workflow

unit-test/cf_chunk_tests.c
- Fix #214 
Rewrites problematic CF_Chunk_InsertChunk tests that occasionally had a buffer overflow due to random number use.
Build and ran unit tests, confirmed passing.  Also confirmed no loss in coverage.
Just fixes random unit test failures on a 32 bit system.
- Hardware: i5/wsl
- Versions: Bundle main + this commit (and app addition)
None
None
=> Fix #214, Resolve buffer overflow in CF_Chunks_InsertChunk unit test

unit-test/cf_chunk_tests.c
- Fix #249
Built and ran unit tests with troublesome seed, got nominal results
None, just avoids possible missing coverage in the unit test for CF_Chunks_FindSmallestSize
- Hardware: i5/wsl
None
None
=> Fix #249, Resolve UT variable coverage results

fsw/platform_inc/cf_platform_cfg.h, fsw/src/cf_app.c, fsw/src/cf_cmd.c, unit-test/cf_cmd_tests.c
- Fix #217
CI
Adds mission rev in startup and noop events
CI
None
None
=> Fix #217, Add mission rev and print in startup and noop events

fsw/src/cf_cfdp_r.c, fsw/src/cf_cmd.c
- Fix #173
CI
Truncates when creating files (avoids stale data if previous file was larger)
CI
None
None
=> Fix #173, Truncate files when created to avoid stale data

.github/pull_request_template.md, CONTRIBUTING.md
Adds link to new CLAs in pull_request_template and contributing.md
- Fixes #254
- Fixes #220
- Fixes https://github.com/nasa/cFS/issues/495
Visually inspected links in fork and in PR template.
All references to CLAs should be updated to the cFS app CLA.
Google Chrome browser
None
Justin Figueroa, ASRC Federal
=> Fix #254, Fix #220, Updates CLA information for Apache 2.0

docs/dox_src/cfs_cf.dox, fsw/src/cf_cfdp_r.c, unit-test/cf_cfdp_r_tests.c
- Fix #131
Switches from OS_rename to OS_mv which supports "rename" across file systems (via copy/delete)
Resets file cached position (from the file open) so it gets recalculated correctly
CI (added unit test asserts)
Should now handle an out-of-order MD, and a tmp dir being on a different filesystem than the final location
CI
Note the functional/CTF test is the full verification of this capability
None
=> Fix #131, Reset file psn and use OS_mv for out-of-order RX MD processing

fsw/src/cf_cmd.c, fsw/src/cf_cmd.h, fsw/src/cf_events.h, unit-test/cf_cmd_tests.c
A clear and concise description of what the contribution is.
Fix #117, an information event message is sent if a command is successful
Fix #155, Remove `CF_CmdCon()`
Ran unit tests
- Behavior Change: All commands now send an information event message if successful
=> Fix #117 #155, Command handling updates

fsw/src/cf_cmd.c, fsw/src/cf_events.h, unit-test/cf_cmd_tests.c
Fix #118 , an error event message is sent if a command is not successful
Ran unit tests
Behavior Change: All commands now send an error event message if unsuccessful
OS: Ubuntu 18.04
=> Fix #118, failed commands send error event message

fsw/src/cf_cmd.c
Fix #283, `CF_CmdCancel_Txn` was being passed to `CF_TsnChanAction()` instead of `CF_CmdAbandon_Txn`
Ran unit tests
When the abandon command is called, it will run `CF_CmdAbandon_Txn`
- OS:Ubuntu 18.04
=> Fix #283, pass correct parameter in Abandon cmd function

fsw/src/cf_app.c, fsw/src/cf_cfdp.c, fsw/src/cf_cfdp_r.c, fsw/src/cf_cfdp_s.c, fsw/src/cf_cfdp_sbintf.c, fsw/src/cf_chunk.c, fsw/src/cf_clist.c, fsw/src/cf_cmd.c, unit-test/cf_cmd_tests.c
Fix #225, replaced all instances of `goto`
Ran unit tests
No impact to behavior
Ubuntu 18.04
=> Fix #225, refactor goto statements

fsw/src/cf_cfdp.c, unit-test/cf_cfdp_tests.c
Fix #285, fixed error in code where semaphore name being blank would skip to the end of `CF_CFDP_InitEngine()`
Ran unit tests
If the semaphore name is blank, continue with function instead of exiting.
=> Fix #285, flatten logic in CF_CFDP_InitEngine() to fix bug

fsw/src/cf_cmd.c, fsw/src/cf_cmd.h, unit-test/cf_cmd_tests.c
Fix #281, remove the CF_CmdAcc() and CF_CmdRej() functions
Ran unit tests
Or no impact to behavior
=> Fix #281, refactored to remove CF_CmdAcc() and CF_CmdRej()

fsw/platform_inc/cf_platform_cfg.h, fsw/src/cf_app.c, fsw/src/cf_cfdp.c, fsw/src/cf_cfdp.h, fsw/src/cf_cfdp_dispatch.c, fsw/src/cf_cfdp_dispatch.h, fsw/src/cf_cfdp_pdu.h, fsw/src/cf_cfdp_r.c, fsw/src/cf_cfdp_r.h, fsw/src/cf_cfdp_s.c, fsw/src/cf_cfdp_sbintf.c, fsw/src/cf_cfdp_types.h, fsw/src/cf_chunk.c, fsw/src/cf_chunk.h, fsw/src/cf_clist.h, fsw/src/cf_cmd.c, fsw/src/cf_cmd.h, fsw/src/cf_codec.c, fsw/src/cf_codec.h, fsw/src/cf_events.h, fsw/src/cf_logical_pdu.h, fsw/src/cf_msg.h
- Fix #18 
- Fix #206 
- Fix #287
CI
None
CI
None
None
=> Fix #18 #206 #287, Comment cleanup and spelling

unit-test/CMakeLists.txt, unit-test/cf_app_tests.c, unit-test/cf_cfdp_dispatch_tests.c, unit-test/cf_cfdp_r_tests.c, unit-test/cf_cfdp_s_tests.c, unit-test/cf_cfdp_sbintf_tests.c, unit-test/cf_cfdp_tests.c, unit-test/cf_cmd_tests.c, unit-test/cf_utils_tests.c, unit-test/utilities/cf_test_utils.c, unit-test/utilities/cf_test_utils.h
- Fix #296 
CI
None, just UT updates/cleanup
CI
None
None
=> Fix #296, Consistent CFE_EVS_SendEvent handling in UT

fsw/src/cf_cfdp_sbintf.c, fsw/src/cf_cfdp_sbintf.h, fsw/src/cf_cfdp_types.h, unit-test/cf_cfdp_sbintf_tests.c
Fix #224
In order to support CF peer to peer transactions, this change will allow incoming PDU packets to be either command or telemetry packets. This is handled in the cf_cfdp_sbintf.c file that handles PDUs wrapped in CCSDS packets.
This change required renaming structures: 
```
CF_PduSendMsg_t to CF_PduTlmMsg_t
CF_PduRecvMsg_t to CF_PduCmdMsg_t
```
This rename makes it less confusing if CF receives a PDU wrapped in a TLM packet, for example. In this case, it would not make sense to receive a "Send" type packet.
In addition to renaming these structures, the typedefs were moved to cf_cfdp_sbint.h as a step toward decoupling the PDU send and receive from the software bus.
By allowing incoming PDU packets to be …
=> Fix #224, support dynamic pdu packets

fsw/src/cf_cmd.c
- Fix #299 
CI
None, text is just more clear
CI
None
None
=> Fix #299, Clarify event text for commands that initiate actions

fsw/src/cf_cmd.c, unit-test/cf_cmd_tests.c
Fix #213, add validation to `CF_CmdTxFile()` and `CF_CmdPlaybackDir()` to prevent negative CFDP class values.
Unit testing
Reject command if CFDP class is negative
- OS:  Ubuntu 18.04
=> Fix #213, updated CFDP class validation

fsw/platform_inc/cf_msgids.h
-Fixes #313
Searched all cf child directories for `CF_CONFIG_TLM_MID` and found no uses of the variable. 100% unit test coverage.
Remove unused `CF_CONFIG_TLM_MID` from cf_msgids.h.
- Ubuntu 18.04
None
If included, identify any third party code and provide text file of license
Justin Figueroa, ASRC Federal
=> Fix #313, removes CF_CONFIG_TLM_MID from cf_msgids.h

unit-test/cf_codec_tests.c
Using the INT32_EQ macro avoids type conversion issues in the event that the int32 type is not equivalent to "int".
Fixes #317
Run all tests
No longer has build failure on systems where int32 != int
RTEMS 4.11
=> Fix #317, use UtAssert_INT32_EQ to check status

fsw/tables/cf_def_config.c
- Fix #319 
CI
Polling disabled by default, avoids messages about the directory not found
CI
Also improved default table comments
None
=> Fix #319, Disable polling directory in default table

fsw/src/cf_cfdp.c
Fixes #30
Amended the only 2 aberrant instances of CF_Transaction_t objects named 'ti', to align them with the other (several hundred) instances named 't'.
None, prior to submission of pull request.
No impact on behavior.
n/a
@thnkslprpt
=> Fix #30, Correct 2 aberrant instances of CF_Transaction_t argument name

fsw/src/cf_cfdp.c, fsw/src/cf_cfdp.h, fsw/src/cf_cfdp_dispatch.c, fsw/src/cf_cfdp_r.c, fsw/src/cf_cfdp_r.h, fsw/src/cf_cfdp_s.c, fsw/src/cf_cfdp_types.h, fsw/src/cf_msg.h, fsw/src/cf_utils.c, fsw/src/cf_utils.h, unit-test/cf_cfdp_dispatch_tests.c, unit-test/cf_cfdp_r_tests.c, unit-test/cf_cfdp_s_tests.c, unit-test/cf_cfdp_tests.c, unit-test/cf_utils_tests.c, unit-test/stubs/cf_cfdp_r_stubs.c, unit-test/stubs/cf_cfdp_stubs.c, unit-test/stubs/cf_cmd_stubs.c, unit-test/stubs/cf_codec_stubs.c, unit-test/stubs/cf_utils_handlers.c, unit-test/stubs/cf_utils_stubs.c, unit-test/utilities/cf_test_alt_handler.c, unit-test/utilities/cf_test_alt_handler.h
Adds a new concept of "transaction status" to replace use of CFDP condition code to indicate the result of a transaction.  To aid in transition this is equivalent in numeric value to the defined CFDP CC values but is extended with additional values for other conditions that can occur in the implementation but do not necessarily result in sending a FIN/EOF PDU.
This also adds setting of Transaction Status for some off-nominal cases where no CFDP CC was set.
Fixes #325 
Build and run all tests, confirm 100% coverage in unit tests for all new/modified functions
Run two instances of CFS running CF and perform file transfer between them, both nominal/successful and also intentionally create an …
=> Fix #325, add more concise transaction status code

unit-test/cf_app_tests.c, unit-test/cf_cmd_tests.c, unit-test/cf_utils_tests.c, unit-test/utilities/cf_test_utils.c
**Checklist**
Fixes #102.
Remaining stray 'C++ style' comments (single line // comments) in CF were removed to changed to 'C-style' comments ( /* ).
A few remaining lines of commented out (unused) code were also removed.
None (comment changes only - no code was modified).
No impact on behavior.
**Contributor Info**
@thnkslprpt
=> Fix #102, Clean up remaining commented-out code

fsw/platform_inc/cf_platform_cfg.h, fsw/src/cf_cfdp.c, unit-test/cf_cfdp_tests.c
Adds a retry loop around OS_CountSemGetIdByName, because if this sem is created by another app there may be some delay until the other app gets to the point where it creates the sem.  This works around the race condition.
A retry limit is also imposed so CF will not spin here forever.
Fixes #184
Build and run tests, check file transfers with BP
Should start up more reliably
Ubuntu 22.04
=> Fix #184, work around throttle sem creation race

fsw/src/cf_cfdp.h, fsw/src/cf_cfdp_r.h, fsw/src/cf_utils.h
Corrects the doxygen for some newly added functions where the parameter names did not match.
Fixes #345
Build documentation
No warnings about parameter name mismatches
Ubuntu 20.04
=> Fix #345, correct doxygen parameters

docs/dox_src/CMakeLists.txt
The documentation requires some artifacts to be in place, this added dependency ensures they are created before doxygen runs.
Fixes #344
Run documentation build
No missing file if this is the first/only target built  (file will be created due to dependency)
Ubuntu 22.04
Requires merging nasa/cfe#2214 and nasa/osal#1341 before this will actually work.
=> Fix #344, add doc-prebuild dependency

fsw/src/cf_cfdp.c
Fix #31 
Unit testing
no impact to behavior
=> Fix #31, reformat bracketed block

fsw/inc/cf_extern_typedefs.h, fsw/inc/cf_msg.h, fsw/inc/cf_tbldefs.h
Fixes #357 - replace quotes with angle brackets in /inc files.
1. Performed build verification testing
2. CI
Dan Knutsen
NASA Goddard
=> Fix #357, Replace quotes with angle brackets in /inc

fsw/inc/cf_platform_cfg.h, fsw/src/cf_cfdp_sbintf.c, unit-test/cf_cfdp_sbintf_tests.c
Adds an option to insert platform-specific padding at the end of CFDP PDU encapsulation.  The padding area may be utilized by the deployment to add arbitrary verification information to the PDU.
Fixes #361
Build and run all tests
Run a CFDP file transfer
None with default config.  New config option allows user to add padding to the end of CFDP PDUs for trailer bytes.
Debian
The extra space is added only to the SB encapsulation of CFDP PDUs, this is not within the CFDP PDU itself (that is, the size inside the CFDP PDU does not include these extra bytes, but the size in the CFE SB message that holds the PDU does …
=> Fix #361, add option for trailer bytes in CFDP PDUs
